[package]
name = "orx-col-card"
version = "0.1.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "Cardinality abstractions over collections"
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-col-card/"
keywords = ["vec", "vector", "algorithm", "trait", "monomorphisation"]
categories = ["data-structures", "algorithms", "no-std"]

[dependencies]
derive-new = { version = "0.7", default-features = false }
# orx-col-dim = { version = "0.1", default-features = false }
orx-col-dim = { path = "../orx-col-dim", default-features = false }
